spring.data.mongodb.uri=mongodb+srv://Dhruv:Dhruv%402005@cluster0.0nrgv67.mongodb.net/cloudshare?retryWrites=true&w=majority

server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://mature-pelican-89.clerk.accounts.dev
clerk.jwks-url=https://mature-pelican-89.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=KQ/C80MpAgOvdQhlQldCJLGILva7UgXo

#file upload config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.level.org.springframework.security=DEBUG

razorpay.key.id=rzp_test_S1tq43tBO3Fm60
razorpay.key.secret=Wjsg5YmE4SPQmyF4hNWChK0Z

cloudinary.cloud-name=dstadrgde
cloudinary.api-key=295244214147837
cloudinary.api-secret=n6DBUpnit8HMEcFauQcOQPx0KGE

