# Server
server.port=8080
server.servlet.context-path=/api/v1.0

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

# Auth
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://mature-pelican-89.clerk.accounts.dev
clerk.jwks-url=https://mature-pelican-89.clerk.accounts.dev/.well-known/jwks.json
clerk.secret.key=${CLERK_SECRET_KEY}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

# File Uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# External Services
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Logs
logging.level.org.springframework.security=DEBUG